---
# tasks file for aide

- name: ENSURE PACKAGES ARE INSTALLED
  yum:
    name: "{{ aide['packages'] }}"
  tags: aide['tags']

- name: ENSURE CONFIGURATION FILE IS PRESENT AND UP TO DATE
  template:
    src: "{{ aide['config']['template']['src'] }}"
    dest: "{{ aide['config']['template']['dest'] }}"
    owner: "{{ aide['config']['template']['owner'] }}"
    group: "{{ aide['config']['template']['group'] }}"
    mode: "{{ aide['config']['template']['mode'] }}"
    backup: "{{ aide['config']['template']['backup'] }}"
    #validate: "{{ aide['config']['template']['validate'] }}"
  tags: aide['tags']

- name: ENSURE AIDE DATABASE IS INITIALIZED
  shell: "aide --init && mv {{ aide['config']['database_out'] }} {{ aide['config']['database'] }}"
  args:
    creates: "{{ aide['config']['database'] }}"
  when: aide['database_init']
  tags: aide['tags']

- name: ENSURE AIDE IS SCHEDULED TO RUN REGULARLY
  cron:
    name: "{{ aide['cron']['name'] }}"
    minute: "{{ aide['cron']['minute'] }}"
    hour: "{{ aide['cron']['hour'] }}"
    day: "{{ aide['cron']['day'] }}"
    month: "{{ aide['cron']['month'] }}"
    weekday: "{{ aide['cron']['weekday'] }}"
    special_time: "{{ aide['cron']['special_time'] }}"
    disabled: "{{ aide['cron']['disabled'] }}"
    state: "{{ aide['cron']['state'] }}"
    user: "{{ aide['cron']['user'] }}"
    job: "{{ aide['cron']['job'] }}"
  tags: aide['tags']
