---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '
